#pragma once

#include "d3d9.h"

// D3D9 texture-stage states used by three-argument combiners and bump/lightmap
// paths. Keeping them typed here lets the WASM compat renderer consume the real
// Direct3D contract without numeric literals while d3d9.h stays minimal.
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_COLORARG0 = static_cast<D3DTEXTURESTAGESTATETYPE>(26);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ALPHAARG0 = static_cast<D3DTEXTURESTAGESTATETYPE>(27);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_RESULTARG = static_cast<D3DTEXTURESTAGESTATETYPE>(28);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT00 = static_cast<D3DTEXTURESTAGESTATETYPE>(7);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT01 = static_cast<D3DTEXTURESTAGESTATETYPE>(8);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT10 = static_cast<D3DTEXTURESTAGESTATETYPE>(9);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT11 = static_cast<D3DTEXTURESTAGESTATETYPE>(10);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVLSCALE = static_cast<D3DTEXTURESTAGESTATETYPE>(22);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVLOFFSET = static_cast<D3DTEXTURESTAGESTATETYPE>(23);
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_CONSTANT = static_cast<D3DTEXTURESTAGESTATETYPE>(32);

constexpr D3DTEXTUREOP D3DTOP_BUMPENVMAP = static_cast<D3DTEXTUREOP>(22);
constexpr D3DTEXTUREOP D3DTOP_BUMPENVMAPLUMINANCE = static_cast<D3DTEXTUREOP>(23);

#ifndef D3DFVF_SPECULAR
#define D3DFVF_SPECULAR 0x080
#endif

#ifndef D3DTA_SPECULAR
#define D3DTA_SPECULAR 0x00000004
#endif
#ifndef D3DTA_TEMP
#define D3DTA_TEMP 0x00000005
#endif
#ifndef D3DTA_CONSTANT
#define D3DTA_CONSTANT 0x00000006
#endif
#ifndef D3DTA_SELECTMASK
#define D3DTA_SELECTMASK 0x0000000F
#endif

inline bool WydD3D9TextureOpUsesArg0(DWORD op) {
  return op == D3DTOP_MULTIPLYADD || op == D3DTOP_LERP;
}

inline DWORD WydD3D9TextureStageResolvedArg0(DWORD op, DWORD arg0) {
  return WydD3D9TextureOpUsesArg0(op) ? arg0 : D3DTA_CURRENT;
}
